version: '3.8'

services:
  db:
    image: postgres:16.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reservation-database
      POSTGRES_USER: k4tfXN9OAGFXWE
      POSTGRES_PASSWORD: XrKO6bek6ojnBM
