spring:
  application:
    name: park-here-challenge
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/reservation-database}
    username: ${DATABASE_USERNAME:k4tfXN9OAGFXWE}
    password: ${DATABASE_PASSWORD:XrKO6bek6ojnBM}
    
configuration-service:
  endpoint: ${CONFIGURATION_SERVICE_ENDPOINT:http://localhost:4010}