spring:
  application:
    name: park-here-challenge
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation-database
    username: k4tfXN9OAGFXWE
    password: XrKO6bek6ojnBM